### PR TITLE
initial dev env

### PR DESCRIPTION
**Pull request by ShirMon**

### CODE REVIEW

**Review by itamar-marom — COMMENTED** [review]
Why do I need to keep this in my git repo ? Are we going to make changes to this ? because if no, why can't I just take it from their repo anytime I want ?

**Comment by ShirMon** [comment]
> Why do I need to keep this in my git repo ? Are we going to make changes to this ? because if no, why can't I just take it from their repo anytime I want ?

This gives us a few things:
- Documentation of what was applied to our cluster and how it was applied (on the readme)
- Consistency of the version of tekton we started to work with. (We can change this to a link to the latest if you want)
- The helm chart has a minor change to enable ingress, and there is a small yaml for the pumba namespace. small changes but gives the comfortable option to apply what is in this folder to a k8s cluster and have a dev env up and running

**Comment by itamar-marom** [comment]
So what will happen when the NEXUS documentation or the version will change ?will I replace all of those files ? Isn't it a better way to just leave a link to the other repo's commit ? (or if you have another solution....) . I think that I don't want to keep a copy... On the other hand, you can still convince me

**Comment by ShirMon** [comment]
> So what will happen when the NEXUS documentation or the version will change ?will I replace all of those files ? Isn't it a better way to just leave a link to the other repo's commit ? (or if you have another solution....) . I think that I don't want to keep a copy... On the other hand, you can still convince me

I mean our documentation of what we need to do to create our dev env.
I was thinking going about it same as package dependencies, so we have a stable running version of tekton or nexus and if there is an update that breaks our pipelines (not really likely) then it will be a headache understanding the cause. Whatever you prefer.

**Comment by itamar-marom** [comment]
Hmmmm....
I understand. But, I still think there is a better way to do it.
@Joshua-Gr Thoughts ?

**Comment by itamar-marom** [comment]
@Joshua-Gr agree, we don't need to save it. We won't update the nexus too much so there is no need.
We'll close this PR but push again with the essential stuff like the NS yaml.

**Pull request closed without merging**
